services:

  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:9090"
    deploy:
      mode: replicated
      replicas: 1